### ISSUE TITLE
Loaded plate data and used nth segmentation.

### ISSUE THREAD

**Issue by FLIMinator** [openmicroscopy/Imperial-FLIMfit#131]
Pressed fit data and then tried to cancel process and the software hangs

![image](https://cloud.githubusercontent.com/assets/7783135/7054167/9fec4352-de32-11e4-9778-6fccc5b6adb5.png)

**Comment by FLIMinator** [comment]
This error  happens when we do segmentation across 200+ fields of view using 'nth segmentation' method. The fitting completes and then hangs when the progress bar says 'processing results'.

Have tvb map,irf shift map, camera offset image loaded into software also.

Performing global analysis, triple fit, grouped 
![segmantation_error_flimfit4 8 0](https://cloud.githubusercontent.com/assets/7783135/7091749/22e9467a-dfa4-11e4-8c35-7881639b1ad0.png)
variables.

**Comment by imunro** [comment]
Hi Hugh. Could you let me have a copy of the data & irf that you were using when this happened please.

**Comment by FLIMinator** [comment]
Hey Ian,

Here is plate data with cells you can segment.

Z:\User Lab Data\Ian Munro\Hughs segmentation testing folder

**Comment by imunro** [comment]
Thanks.

**Comment by imunro** [comment]
@swarren I don't think this is the problem here but Hugh's screen shot shows a a problem with getPixelPosition and I think there are 2 old copies of the  GUIILayout stuff at https://github.com/openmicroscopy/Imperial-FLIMfit/tree/master/FLIMfitFrontEnd/HelperFunctions/GUILayout  and https://github.com/openmicroscopy/Imperial-FLIMfit/tree/master/FLIMfitFrontEnd/HelperFunctions/GUILayout-v1p17  Do you know of any reason not to delete these now?

**Comment by seanwarren** [comment]
Nope let's clean those up

On 18 Apr 2015 02:15, imunro <notifications@github.com> wrote:

@swarren<https://github.com/swarren> I don't think this is the problem here but Hugh's screen shot shows a a problem with getPixelPosition and I think there are 2 old copies of the GUIILayout stuff at https://github.com/openmicroscopy/Imperial-FLIMfit/tree/master/FLIMfitFrontEnd/HelperFunctions/GUILayout and https://github.com/openmicroscopy/Imperial-FLIMfit/tree/master/FLIMfitFrontEnd/HelperFunctions/GUILayout-v1p17 Do you know of any reason not to delete these now?

**Comment by imunro** [comment]
Cool! Will do.

Ian


On 18 Apr 2015, at 09:40, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:

Nope let's clean those up

On 18 Apr 2015 02:15, imunro <notifications@github.com<mailto:notifications@github.com>> wrote:

@swarren<https://github.com/swarren> I don't think this is the problem here but Hugh's screen shot shows a a problem with getPixelPosition and I think there are 2 old copies of the GUIILayout stuff at https://github.com/openmicroscopy/Imperial-FLIMfit/tree/master/FLIMfitFrontEnd/HelperFunctions/GUILayout and https://github.com/openmicroscopy/Imperial-FLIMfit/tree/master/FLIMfitFrontEnd/HelperFunctions/GUILayout-v1p17 Do you know of any reason not to delete these now?

**Comment by FLIMinator** [comment]
Hi Ian,

Has this issue be resolved in version 4.8.1?

**Comment by seanwarren** [comment]
This should be fixed now

On 3 May 2015 04:14, FLIMinator <notifications@github.com> wrote:

Hi Ian,

Has this issue be resolved in version 4.8.1?

**Comment by imunro** [comment]
I'm going to assume Sean's correct and close.
